[project]
name = "cav-class"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "carla>=0.9.15",
    "numpy>=1.24.4",
    "pygame>=2.6.1",
]
